"""initial_property_tables

Revision ID: 25fd903281e5
Revises: 
Create Date: 2019-01-16 19:49:42.948323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fd903281e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_key', sa.String(), nullable=False),
    sa.Column('todays_date', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('municipal_district', sa.String(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('tax_bill_number', sa.String(), nullable=True),
    sa.Column('property_class', sa.String(), nullable=True),
    sa.Column('special_tax_district', sa.String(), nullable=True),
    sa.Column('subdivision_name', sa.String(), nullable=True),
    sa.Column('land_area_sq_ft', sa.String(), nullable=True),
    sa.Column('zoning_district', sa.String(), nullable=True),
    sa.Column('building_area_sq_ft', sa.String(), nullable=True),
    sa.Column('square', sa.String(), nullable=True),
    sa.Column('lot', sa.String(), nullable=True),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('folio', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('parcel_map', sa.String(), nullable=True),
    sa.Column('legal_description', sa.String(), nullable=True),
    sa.Column('assessment_area', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('sale_transfer_date', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('grantor', sa.String(), nullable=True),
    sa.Column('grantee', sa.String(), nullable=True),
    sa.Column('notarial_archive_number', sa.String(), nullable=True),
    sa.Column('instrument_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('land_value', sa.String(), nullable=True),
    sa.Column('building_value', sa.String(), nullable=True),
    sa.Column('total_value', sa.String(), nullable=True),
    sa.Column('assessed_land_value', sa.String(), nullable=True),
    sa.Column('assessed_building_value', sa.String(), nullable=True),
    sa.Column('total_assessed_value', sa.String(), nullable=True),
    sa.Column('homestead_exemption_value', sa.String(), nullable=True),
    sa.Column('taxable_assessment', sa.String(), nullable=True),
    sa.Column('age_freeze', sa.String(), nullable=True),
    sa.Column('disability_freeze', sa.String(), nullable=True),
    sa.Column('assmnt_change', sa.String(), nullable=True),
    sa.Column('tax_contract', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_values')
    op.drop_table('property_transfers')
    op.drop_table('properties')
    # ### end Alembic commands ###
