"""update_property_fields

Revision ID: a91f96702e22
Revises: 25fd903281e5
Create Date: 2019-01-16 19:51:33.633171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91f96702e22'
down_revision = '25fd903281e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('lot_folio', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('revised_bldg_area_sqft', sa.String(), nullable=True))
    op.drop_column('properties', 'lot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('lot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('properties', 'revised_bldg_area_sqft')
    op.drop_column('properties', 'lot_folio')
    # ### end Alembic commands ###
